config/routes.rb
Rails.application.routes.draw do
  resources :pizzaorders
  resources :deliveryinfos
  resources :orders
  resources :pizzas
  resources :recipeingredients
  resources :recipes
  resources :crusts
  resources :ingredients
  root 'home#index'
  get 'home/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crust.rb
class Crust < ApplicationRecord
end

app/models/deliveryinfo.rb
class Deliveryinfo < ApplicationRecord
  belongs_to :order

  validates :name, presence: true
  validates :address1, presence: true
  validates :address2, presence: true
  validates :phone, numericality: { only_integer: true }, presence: true

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  validates :payment, presence: true
end

app/models/pizza.rb
class Pizza < ApplicationRecord
  belongs_to :crust
  belongs_to :recipe
  belongs_to :user
end

app/models/pizzaorder.rb
class Pizzaorder < ApplicationRecord
  belongs_to :order
  belongs_to :pizza
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients
end

app/models/recipeingredient.rb
class Recipeingredient < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/crusts_controller.rb
class CrustsController < ApplicationController
  before_action :set_crust, only: [:show, :edit, :update, :destroy]

  # GET /crusts
  # GET /crusts.json
  def index
    @crusts = Crust.all
  end

  # GET /crusts/1
  # GET /crusts/1.json
  def show
  end

  # GET /crusts/new
  def new
    @crust = Crust.new
  end

  # GET /crusts/1/edit
  def edit
  end

  # POST /crusts
  # POST /crusts.json
  def create
    @crust = Crust.new(crust_params)

    respond_to do |format|
      if @crust.save
        format.html { redirect_to @crust, notice: 'Crust was successfully created.' }
        format.json { render :show, status: :created, location: @crust }
      else
        format.html { render :new }
        format.json { render json: @crust.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crusts/1
  # PATCH/PUT /crusts/1.json
  def update
    respond_to do |format|
      if @crust.update(crust_params)
        format.html { redirect_to @crust, notice: 'Crust was successfully updated.' }
        format.json { render :show, status: :ok, location: @crust }
      else
        format.html { render :edit }
        format.json { render json: @crust.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crusts/1
  # DELETE /crusts/1.json
  def destroy
    @crust.destroy
    respond_to do |format|
      format.html { redirect_to crusts_url, notice: 'Crust was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crust
      @crust = Crust.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crust_params
      params.require(:crust).permit(:name, :price)
    end
end

app/controllers/deliveryinfos_controller.rb
class DeliveryinfosController < ApplicationController
  before_action :set_deliveryinfo, only: [:show, :edit, :update, :destroy]

  # GET /deliveryinfos
  # GET /deliveryinfos.json
  def index
    @deliveryinfos = Deliveryinfo.all
  end

  # GET /deliveryinfos/1
  # GET /deliveryinfos/1.json
  def show
    @pizzas = Pizza.all
  end

  # GET /deliveryinfos/new
  def new
    @deliveryinfo = Deliveryinfo.new
  end

  # GET /deliveryinfos/1/edit
  def edit
  end

  # POST /deliveryinfos
  # POST /deliveryinfos.json
  def create
    @deliveryinfo = Deliveryinfo.new(deliveryinfo_params)

    respond_to do |format|
      if @deliveryinfo.save
        format.html { redirect_to @deliveryinfo, notice: 'Delivery information was successfully added.' }
        format.json { render :show, status: :created, location: @deliveryinfo }
      else
        format.html { render :new }
        format.json { render json: @deliveryinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deliveryinfos/1
  # PATCH/PUT /deliveryinfos/1.json
  def update
    respond_to do |format|
      if @deliveryinfo.update(deliveryinfo_params)
        format.html { redirect_to @deliveryinfo, notice: 'Deliveryinfo was successfully updated.' }
        format.json { render :show, status: :ok, location: @deliveryinfo }
      else
        format.html { render :edit }
        format.json { render json: @deliveryinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deliveryinfos/1
  # DELETE /deliveryinfos/1.json
  def destroy
    @deliveryinfo.destroy
    respond_to do |format|
      format.html { redirect_to deliveryinfos_url, notice: 'Deliveryinfo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deliveryinfo
      @deliveryinfo = Deliveryinfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deliveryinfo_params
      params.require(:deliveryinfo).permit(:name, :address1, :address2, :phone, :order_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.all
    @recing = Recipeingredient.all
    @ingredients = Ingredient.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @pizzas = Pizza.all
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:user_id, :payment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crusts_helper.rb
module CrustsHelper
end

app/helpers/deliveryinfos_helper.rb
module DeliveryinfosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pizzaorders_helper.rb
module PizzaordersHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/deliveryinfos/_form.html.erb
<%= form_with(model: deliveryinfo, local: true) do |form| %>
  <% if deliveryinfo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(deliveryinfo.errors.count, "error") %> prohibited this deliveryinfo from being saved:</h2>

      <ul>
      <% deliveryinfo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :deliveryinfo_name %>
  </div>

  <div class="field">
    <%= form.label :address1 %>
    <%= form.text_field :address1, id: :deliveryinfo_address1 %>
  </div>

  <div class="field">
    <%= form.label :address2 %>
    <%= form.text_field :address2, id: :deliveryinfo_address2 %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :deliveryinfo_phone %>
  </div>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.text_field :order_id, id: :deliveryinfo_order_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/deliveryinfos/edit.html.erb
<h1>Editing Deliveryinfo</h1>

<%= render 'form', deliveryinfo: @deliveryinfo %>

<%= link_to 'Show', @deliveryinfo %> |
<%= link_to 'Back', deliveryinfos_path %>

app/views/deliveryinfos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Deliveryinfos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address1</th>
      <th>Address2</th>
      <th>Phone</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deliveryinfos.each do |deliveryinfo| %>
      <tr>
        <td><%= deliveryinfo.name %></td>
        <td><%= deliveryinfo.address1 %></td>
        <td><%= deliveryinfo.address2 %></td>
        <td><%= deliveryinfo.phone %></td>
        <td><%= deliveryinfo.order %></td>
        <td><%= link_to 'Show', deliveryinfo %></td>
        <td><%= link_to 'Edit', edit_deliveryinfo_path(deliveryinfo) %></td>
        <td><%= link_to 'Destroy', deliveryinfo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deliveryinfo', new_deliveryinfo_path %>

app/views/deliveryinfos/new.html.erb
<h1>New Deliveryinfo</h1>

<%= render 'form', deliveryinfo: @deliveryinfo %>

<%= link_to 'Back', deliveryinfos_path %>

app/views/deliveryinfos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @deliveryinfo.name %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @deliveryinfo.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @deliveryinfo.address2 %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @deliveryinfo.phone %>
</p>

<p>
  <strong>Order:</strong>
  <%= @deliveryinfo.order.id %>
</p>

<% @pizzas.where(user_id: current_user).each do |pizza| %>
  <%= form_for Pizzaorder.new do |po| %>
    <%= po.hidden_field :order_id, :value => @deliveryinfo.order_id %>
    <%= po.hidden_field :pizza_id, :value => pizza.id %>
    <%= po.submit "Confirm Order", class:"btn btn-primary"%>
  <% end %>
<% end %>

<!--
<%= link_to 'Edit', edit_deliveryinfo_path(@deliveryinfo) %> |
<%= link_to 'Back', deliveryinfos_path %>-->