config/routes.rb
Rails.application.routes.draw do
  resources :pizzaorders
  resources :deliveryinfos
  resources :orders
  resources :pizzas
  resources :recipeingredients
  resources :recipes
  resources :crusts
  resources :ingredients
  root 'home#index'
  get 'home/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crust.rb
class Crust < ApplicationRecord
end

app/models/deliveryinfo.rb
class Deliveryinfo < ApplicationRecord
  belongs_to :order

  validates :name, presence: true
  validates :address1, presence: true
  validates :address2, presence: true
  validates :phone, numericality: { only_integer: true }, presence: true

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  validates :payment, presence: true
end

app/models/pizza.rb
class Pizza < ApplicationRecord
  belongs_to :crust
  belongs_to :recipe
  belongs_to :user
end

app/models/pizzaorder.rb
class Pizzaorder < ApplicationRecord
  belongs_to :order
  belongs_to :pizza
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients
end

app/models/recipeingredient.rb
class Recipeingredient < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/crusts_controller.rb
class CrustsController < ApplicationController
  before_action :set_crust, only: [:show, :edit, :update, :destroy]

  # GET /crusts
  # GET /crusts.json
  def index
    @crusts = Crust.all
  end

  # GET /crusts/1
  # GET /crusts/1.json
  def show
  end

  # GET /crusts/new
  def new
    @crust = Crust.new
  end

  # GET /crusts/1/edit
  def edit
  end

  # POST /crusts
  # POST /crusts.json
  def create
    @crust = Crust.new(crust_params)

    respond_to do |format|
      if @crust.save
        format.html { redirect_to @crust, notice: 'Crust was successfully created.' }
        format.json { render :show, status: :created, location: @crust }
      else
        format.html { render :new }
        format.json { render json: @crust.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crusts/1
  # PATCH/PUT /crusts/1.json
  def update
    respond_to do |format|
      if @crust.update(crust_params)
        format.html { redirect_to @crust, notice: 'Crust was successfully updated.' }
        format.json { render :show, status: :ok, location: @crust }
      else
        format.html { render :edit }
        format.json { render json: @crust.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crusts/1
  # DELETE /crusts/1.json
  def destroy
    @crust.destroy
    respond_to do |format|
      format.html { redirect_to crusts_url, notice: 'Crust was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crust
      @crust = Crust.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crust_params
      params.require(:crust).permit(:name, :price)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.all
    @recing = Recipeingredient.all
    @ingredients = Ingredient.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @pizzas = Pizza.all
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:user_id, :payment)
    end
end

app/controllers/pizzaorders_controller.rb
class PizzaordersController < ApplicationController
  before_action :set_pizzaorder, only: [:show, :edit, :update, :destroy]

  # GET /pizzaorders
  # GET /pizzaorders.json
  def index
    @pizzaorders = Pizzaorder.all
  end

  # GET /pizzaorders/1
  # GET /pizzaorders/1.json
  def show
  end

  # GET /pizzaorders/new
  def new
    @pizzaorder = Pizzaorder.new
  end

  # GET /pizzaorders/1/edit
  def edit
  end

  # POST /pizzaorders
  # POST /pizzaorders.json
  def create
    @pizzaorder = Pizzaorder.new(pizzaorder_params)

    respond_to do |format|
      if @pizzaorder.save
        format.html { redirect_to @pizzaorder, notice: 'Pizzaorder was successfully created.' }
        format.json { render :show, status: :created, location: @pizzaorder }
      else
        format.html { render :new }
        format.json { render json: @pizzaorder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pizzaorders/1
  # PATCH/PUT /pizzaorders/1.json
  def update
    respond_to do |format|
      if @pizzaorder.update(pizzaorder_params)
        format.html { redirect_to @pizzaorder, notice: 'Pizzaorder was successfully updated.' }
        format.json { render :show, status: :ok, location: @pizzaorder }
      else
        format.html { render :edit }
        format.json { render json: @pizzaorder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pizzaorders/1
  # DELETE /pizzaorders/1.json
  def destroy
    @pizzaorder.destroy
    respond_to do |format|
      format.html { redirect_to pizzaorders_url, notice: 'Pizzaorder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pizzaorder
      @pizzaorder = Pizzaorder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pizzaorder_params
      params.require(:pizzaorder).permit(:order_id, :pizza_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crusts_helper.rb
module CrustsHelper
end

app/helpers/deliveryinfos_helper.rb
module DeliveryinfosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pizzaorders_helper.rb
module PizzaordersHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/pizzaorders/_form.html.erb
<%= form_with(model: pizzaorder, local: true) do |form| %>
  <% if pizzaorder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pizzaorder.errors.count, "error") %> prohibited this pizzaorder from being saved:</h2>

      <ul>
      <% pizzaorder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.text_field :order_id, id: :pizzaorder_order_id %>
  </div>

  <div class="field">
    <%= form.label :pizza_id %>
    <%= form.text_field :pizza_id, id: :pizzaorder_pizza_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pizzaorders/edit.html.erb
<h1>Editing Pizzaorder</h1>

<%= render 'form', pizzaorder: @pizzaorder %>

<%= link_to 'Show', @pizzaorder %> |
<%= link_to 'Back', pizzaorders_path %>

app/views/pizzaorders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pizzaorders</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Pizza</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pizzaorders.each do |pizzaorder| %>
      <tr>
        <td><%= pizzaorder.order %></td>
        <td><%= pizzaorder.pizza %></td>
        <td><%= link_to 'Show', pizzaorder %></td>
        <td><%= link_to 'Edit', edit_pizzaorder_path(pizzaorder) %></td>
        <td><%= link_to 'Destroy', pizzaorder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pizzaorder', new_pizzaorder_path %>

app/views/pizzaorders/new.html.erb
<h1>New Pizzaorder</h1>

<%= render 'form', pizzaorder: @pizzaorder %>

<%= link_to 'Back', pizzaorders_path %>

app/views/pizzaorders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @pizzaorder.order %>
</p>

<p>
  <strong>Pizza:</strong>
  <%= @pizzaorder.pizza %>
</p>

<%= link_to 'Edit', edit_pizzaorder_path(@pizzaorder) %> |
<%= link_to 'Back', pizzaorders_path %>